box_image: ubu24
network:
  bridge_adapter: "en0: Wi-Fi"
  subnet: 172.21.30
  ip_offset: 10
  cidr: 16
  gateway: 172.21.0.1
k8s:
  k8s_version: 1.33.3
  containerd_version: 2.1.3
  pod_subnet: 10.244.0.0/16
  service_subnet: 10.96.0.0/16
  kubeproxy: "false"
node_counts:
  control_plane: 1
  worker: 1
node_resources:
  control_plane:
    cpu: 2
    memory: 4096
  worker:
    cpu: 2
    memory: 4096
